---

domain: s.todo.to.it

hosts:
  - hostname: server
    environment: dev
    location: trn.it
    number: 1
    project: none
    purpose: app
  - hostname: elserver
    environment: prd
    location: trn.it
    number: 1
    project: none
    purpose: app